export const permissions = {
  cars: {
    list: "public",
    getOne: [
      "superadmin",
      "admin",
      "manager",
      "owner",
      "driver",
      "officer",
      "coordinator",
    ],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
  },
  drivers: {
    list: [
      "superadmin",
      "admin",
      "manager",
      "owner",
      "driver",
      "officer",
      "coordinator",
    ],
    getOne: [
      "superadmin",
      "admin",
      "manager",
      "owner",
      "driver",
      "officer",
      "coordinator",
    ],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
  },
  employees: {
    list: ["superadmin", "admin", "manager"],
    getOne: ["superadmin", "admin", "manager", "officer", "coordinator"],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
  },
  owners: {
    list: ["admin", "manager", "owner"],
    getOne: ["admin", "manager", "owner"],
    create: ["admin", "manager", "owner"],
    update: ["admin", "manager", "owner"],
    remove: ["admin", "manager", "owner"],
  },
  passengers: {
    list: "public",
    getOne: ["admin", "manager", "coordinator", "passenger"],
    create: ["admin", "passenger", "coordinator"],
    update: ["admin", "passenger", "coordinator"],
    remove: ["admin", "manager"],
  },
  programs: {
    list: "public",
    getOne: [
      "admin",
      "manager",
      "coordinator",
      "officer",
      "driver",
      "owner",
      "passenger",
    ],
    create: ["admin", "manager", "coordinator"],
    update: ["admin", "manager", "coordinator"],
    remove: ["admin", "manager", "coordinator"],
  },

  payments: {
    list: ["admin", "manager", "officer", "driver", "owner"],
    getOne: ["admin", "manager", "coordinator", "driver", "owner"],
    update: ["admin", "officer"],
    create: ["admin", "officer"],
    remove: ["admin"],
  },

  penalities: {
    list: ["admin", "manager", "officer", "driver", "owner"],
    getOne: ["admin", "manager", "coordinator", "driver", "owner"],
    update: ["admin", "officer"],
    create: ["admin", "officer"],
    remove: ["admin"],
  },

  routs: {
    list: "public",
    getOne: [
      "admin",
      "manager",
      "coordinator",
      "officer",
      "driver",
      "owner",
      "passenger",
    ],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
    fetchRouts: "public",
  },
  subrouts: {
    list: "public",
    getOne: [
      "admin",
      "manager",
      "coordinator",
      "passenger",
      "driver",
      "owner",
      "passenger",
    ],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
    fetchRouts: "public",
  },
  rules: {
    list: "public",
    getOne: "public",
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
  },

  reports: {
    list: [
      "admin",
      "manager",
      "passenger",
      "coordinator",
      "officer",
      "driver",
      "owner",
    ],
    getOne: [
      "admin",
      "manager",
      "passenger",
      "coordinator",
      "officer",
      "driver",
      "owner",
    ],
    create: ["admin", "manager", "passenger"],
    update: ["admin", "manager", "passenger"],
    remove: ["admin", "manager", "passenger"],
  },

  tickets: {
    list: [
      "admin",
      "manager",
      "passenger",
      "coordinator",
      "officer",
      "driver",
      "owner",
    ],
    getOne: [
      "admin",
      "manager",
      "passenger",
      "coordinator",
      "officer",
      "driver",
      "owner",
    ],
    create: ["admin", "manager", "coordinator", "passenger"],
    update: ["admin", "manager", "coordinator"],
    remove: ["admin", "manager", "passenger", "coordinator"],
    listTicketByProgram: ["admin", "manager", "coordinator", "passenger"],
  },
  cancelledTickets: {
    list: [
      "admin",
      "manager",
      "passenger",
      "coordinator",
      "officer",
      "driver",
      "owner",
    ],
    getOne: [
      "admin",
      "manager",
      "passenger",
      "coordinator",
      "officer",
      "driver",
      "owner",
    ],
    create: ["admin", "manager", "coordinator"],
    update: ["admin", "manager", "coordinator"],
    remove: ["admin", "manager", "passenger", "coordinator"],
    listTicketByProgram: ["admin", "manager", "coordinator"],
  },
  trafficPolice: {
    list: ["admin", "manager", "passenger", "coordinator", "officer"],
    getOne: ["admin", "manager", "passenger", "coordinator", "officer"],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
  },

  trafficAssignments: {
    list: ["admin", "manager", "passenger", "coordinator", "officer"],
    getOne: ["admin", "manager", "passenger", "coordinator", "officer"],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
  },
  // tarrifs: {
  //   list: ["admin", "manager", "passenger", "coordinator", "officer"],
  //   getOne: ["admin", "manager", "passenger", "coordinator", "officer"],
  //   create: ["admin", "manager"],
  //   update: ["admin", "manager"],
  //   remove: ["admin", "manager"],
  // },
  country: {
    list: "public",
    getOne: ["admin", "manager", "passenger", "coordinator", "officer"],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
  },
  state: {
    list: "public",
    getOne: ["admin", "manager", "passenger", "coordinator", "officer"],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
    get_State_By_Country: ["admin", "manager"],
  },
  zone: {
    list: "public",
    getOne: [
      "admin",
      "manager",
      "passenger",
      "coordinator",
      "officer",
      "driver",
    ],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
    get_State_By_Country: ["admin", "manager"],
  },
  wereda: {
    list: "public",
    getOne: [
      "admin",
      "manager",
      "passenger",
      "coordinator",
      "officer",
      "driver",
    ],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
    get_State_By_Country: ["admin", "manager"],
  },
  city: {
    list: "public",
    getOne: [
      "admin",
      "manager",
      "passenger",
      "coordinator",
      "officer",
      "driver",
    ],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
    get_State_By_Country: ["admin", "manager"],
  },
  user: {
    list: ["admin", "manager", "passenger", "coordinator", "officer"],
    getOne: ["admin", "manager", "passenger", "coordinator", "officer"],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
  },
  recycleBin: {
    list: ["admin", "manager", "passenger", "coordinator", "officer"],
    restore: ["admin", "manager", "passenger", "coordinator", "officer"],
  },
  violation: {
    list: ["admin", "manager", "passenger", "coordinator", "officer", "driver"],
    getOne: ["admin", "manager", "passenger", "coordinator", "officer"],
    create: ["admin", "manager", "passenger"],
    update: ["admin", "manager", "passenger"],
    remove: ["admin", "manager"],
    fetchRouts: "public",
  },
  tarrif: {
    list: ["admin", "manager", "passenger", "coordinator", "officer", "driver"],
    getOne: ["admin", "manager", "passenger", "coordinator", "officer"],
    create: ["admin", "manager"],
    update: ["admin", "manager"],
    remove: ["admin", "manager"],
  },
};
